//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arenda()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> D_vidachi { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_sotrudnika { get; set; }
        public Nullable<System.DateTime> D_sdachi { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
    }
}
